# Generated by Django 4.2.11 on 2026-01-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_assistantmemory_delete_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmemory',
            name='memory_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assistantmemory',
            name='memory_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
