# Generated by Django 4.2.11 on 2026-02-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_dailymemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmemory',
            name='code_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
