# Generated by Django 4.2.11 on 2026-02-23 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_assistantmemory_code_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantmemory',
            name='code_file',
        ),
    ]
