# Generated by Django 4.2.11 on 2026-03-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_remove_assistantmemory_code_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmemory',
            name='mood',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
